name: remodelingCI

on:
  push:
    branches:
      - '*'
  pull-request:
    branches:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install require packages
      run: sudo apt-get install -f shellcheck

    - name: Run shell check
      run: |
        make shellcheck
        popd
    - name: Run Docker check
      run: |
        make docker-lint
        popd
